var otypeDescs = {
  "EmO":"Emission Object",
  "SB*":"Spectroscopic binary",
  "rB":"radio Burst",
  "a2*":"Variable Star of alpha2 CVn type",
  "Mi*":"Variable Star of Mira Cet type",
  "XB*":"X-ray Binary",
  "BD?":"Brown Dwarf Candidate",
  "mul":"Composite object",
  "TT?":"T Tau star Candidate",
  "*":"Star",
  "As*":"Association of Stars",
  "LLS":"Lyman limit system",
  "SCG":"Supercluster of Galaxies",
  "smm":"sub-millimetric source",
  "DQ*":"CV DQ Her type (intermediate polar)",
  "BL?":"Possible BL Lac",
  "s?r":"Possible Red supergiant star",
  "bCG":"Blue compact Galaxy",
  "red":"Very red source",
  "CGb":"Cometary Globule",
  "HI":"HI (21cm) source",
  "MGr":"Moving Group",
  "SNR":"SuperNova Remnant",
  "BS?":"Candidate blue Straggler Star",
  "s?b":"Possible Blue supergiant star",
  "GNe":"Galactic Nebula",
  "*i*":"Star in double system",
  "RNe":"Reflection Nebula",
  "WR?":"Possible Wolf-Rayet Star",
  "SFR":"Star forming region",
  "out":"Outflow",
  "..?":"Candidate objects",
  "cor":"Dense core",
  "Cld":"Cloud",
  "ClG":"Cluster of Galaxies",
  "GlC":"Globular Cluster",
  "XB?":"X-ray binary Candidate",
  "Gl?":"Possible Globular Cluster",
  "RB?":"Possible Red Giant Branch star",
  "mR":"metric Radio-source",
  "?":"Object of unknown nature",
  "Er*":"Eruptive variable Star",
  "pr*":"Pre-main sequence Star",
  "WD*":"White Dwarf",
  "QSO":"Quasar",
  "CV?":"Cataclysmic Binary Candidate",
  "Q?":"Possible Quasar",
  "SBG":"Starburst Galaxy",
  "LeG":"Gravitationally Lensed Image of a Galaxy",
  "BLL":"BL Lac - type object",
  "Sy1":"Seyfert 1 Galaxy",
  "Le?":"Possible gravitational lens",
  "Sy2":"Seyfert 2 Galaxy",
  "Bla":"Blazar",
  "PN?":"Possible Planetary Nebula",
  "SN?":"SuperNova Candidate",
  "SyG":"Seyfert Galaxy",
  "Be?":"Possible Be Star",
  "Ce?":"Possible Cepheid",
  "gD*":"Variable Star of gamma Dor type",
  "G?":"Possible Galaxy",
  "sh":"HI shell",
  "PN":"Planetary Nebula",
  "N*?":"Neutron Star Candidate",
  "LIN":"LINER-type Active Galaxy Nucleus",
  "UV":"UV-emission source",
  "cm":"centimetric Radio-source",
  "AGN":"Active Galaxy Nucleus",
  "IG":"Interacting Galaxies",
  "LeQ":"Gravitationally Lensed Image of a Quasar",
  "S*?":"Possible S Star",
  "BNe":"Bright Nebula",
  "Ae?":"Possible Herbig Ae/Be Star",
  "V*":"Variable Star",
  "LeI":"Gravitationally Lensed Image",
  "rG":"Radio Galaxy",
  "OVV":"Optically Violently Variable object",
  "EmG":"Emission-line galaxy",
  "Bz?":"Possible Blazar",
  "HV*":"High-velocity Star",
  "RC*":"Variable Star of R CrB type",
  "LM?":"Low-mass star candidate",
  "TT*":"T Tau-type Star",
  "*iN":"Star in Nebula",
  "BS*":"Blue Straggler Star",
  "H2G":"HII Galaxy",
  "bL*":"Eclipsing binary of beta Lyr type (semi-detached)",
  "Pe*":"Peculiar Star",
  "mm":"millimetric Radio-source",
  "cC*":"Classical Cepheid (delta Cep type)",
  "mAL":"metallic Absorption Line system",
  "DLA":"Damped Ly-alpha Absorption Line system",
  "EB*":"Eclipsing binary",
  "LyA":"Ly alpha Absorption Line system",
  "ALS":"Absorption Line system",
  "gLS":"Gravitational Lens System (lens+images)",
  "AB*":"Asymptotic Giant Branch Star (He-burning)",
  "N*":"Confirmed Neutron Star",
  "WD?":"White Dwarf Candidate",
  "SC?":"Possible Supercluster of Galaxies",
  "GiP":"Galaxy in Pair of Galaxies",
  "HB*":"Horizontal Branch Star",
  "S*":"S Star",
  "GiG":"Galaxy in Group of Galaxies",
  "gam":"gamma-ray source",
  "PoC":"Part of Cloud",
  "BAL":"Broad Absorption Line system",
  "No*":"Nova",
  "Psr":"Pulsar",
  "Pl?":"Extra-solar Planet Candidate",
  "vid":"Underdense region of the Universe",
  "OH?":"Possible Star with envelope of OH/IR type",
  "MoC":"Molecular Cloud",
  "G":"Galaxy",
  "Pl":"Extra-solar Confirmed Planet",
  "**?":"Physical Binary Candidate",
  "BH?":"Black Hole Candidate",
  "of?":"Outflow candidate",
  "C*":"Carbon Star",
  "PoG":"Part of a Galaxy",
  "WU*":"Eclipsing binary of W UMa type (contact binary)",
  "HVC":"High-velocity Cloud",
  "pA*":"Post-AGB Star (proto-PN)",
  "sr*":"Semi-regular pulsating Star",
  "ULX":"Ultra-luminous X-ray source",
  "UX?":"Ultra-luminous X-ray candidate",
  "SX*":"Variable Star of SX Phe type (subdwarf)",
  "bC*":"Variable Star of beta Cep type",
  "RI*":"Variable Star with rapid variations",
  "RC?":"Variable Star of R CrB type candiate",
  "HX?":"High-Mass X-ray binary Candidate",
  "LM*":"Low-mass star (M<1solMass)",
  "dS*":"Variable Star of delta Sct type",
  "sv?":"Semi-regular variable candidate",
  "LX?":"Low-Mass X-ray binary Candidate",
  "PM*":"High proper-motion Star",
  "ISM":"Interstellar matter",
  "WR*":"Wolf-Rayet Star",
  "RR*":"Variable Star of RR Lyr type",
  "OpC":"Open (galactic) Cluster",
  "sg?":"Possible Supergiant star",
  "Ae*":"Herbig Ae/Be star",
  "sg*":"Evolved supergiant star",
  "RS*":"Variable of RS CVn type",
  "BY*":"Variable of BY Dra type",
  "Ro*":"Rotationally variable Star",
  "RV*":"Variable Star of RV Tau type",
  "FU*":"Variable Star of FU Ori type",
  "FIR":"Far-IR source  (\\lambda >= 30 {\\mu}m)",
  "WV*":"Variable Star of W Vir type",
  "C*?":"Possible Carbon Star",
  "*iC":"Star in Cluster",
  "Rad":"Radio-source",
  "ev":"transient event",
  "DN*":"Dwarf Nova",
  "LXB":"Low Mass X-ray Binary",
  "Or*":"Variable Star of Orion Type",
  "Ir*":"Variable Star of irregular type",
  "AG?":"Possible Active Galaxy Nucleus",
  "HXB":"High Mass X-ray Binary",
  "Ce*":"Cepheid variable Star",
  "CV*":"Cataclysmic Variable Star",
  "CH*":"Star with envelope of CH type",
  "OH*":"OH/IR star",
  "BD*":"Brown Dwarf (M<0.08solMass)",
  "*iA":"Star in Association",
  "ZZ*":"Pulsating White Dwarf",
  "SN*":"SuperNova",
  "CGG":"Compact Group of Galaxies",
  "glb":"Globule (low-mass dark cloud)",
  "s?y":"Possible Yellow supergiant star",
  "s*y":"Yellow supergiant star",
  "pA?":"Post-AGB Star Candidate",
  "HH":"Herbig-Haro Object",
  "pr?":"Pre-main sequence Star Candidate",
  "Mi?":"Mira candidate",
  "gLe":"Gravitational Lens",
  "Be*":"Be Star",
  "EB?":"Eclipsing Binary Candidate",
  "HB?":"Possible Horizontal Branch Star",
  "**":"Double or multiple star",
  "Pu*":"Pulsating variable Star",
  "AB?":"Asymptotic Giant Branch Star candidate",
  "NIR":"Near-IR source (\\lambda < 10 {\\mu}m)",
  "blu":"Blue object",
  "RR?":"Possible Star of RR Lyr type",
  "GiC":"Galaxy in Cluster of Galaxies",
  "V*?":"Star suspected of Variability",
  "C?*":"Possible (open) star cluster",
  "LSB":"Low Surface Brightness Galaxy",
  "s*r":"Red supergiant star",
  "BiC":"Brightest galaxy in a Cluster (BCG)",
  "reg":"Region defined in the sky",
  "No?":"Nova Candidate",
  "IR":"Infra-Red source",
  "SR?":"SuperNova Remnant Candidate",
  "Em*":"Emission-line Star",
  "Mas":"Maser",
  "C?G":"Possible Cluster of Galaxies",
  "Lev":"(Micro)Lensing Event",
  "Pec?":"Possible Peculiar Star",
  "CH?":"Possible Star with envelope of CH type",
  "LP?":"Long Period Variable candidate",
  "St*":"Stellar Stream",
  "su*":"Sub-stellar object",
  "grv":"Gravitational Source",
  "NL*":"Nova-like Star",
  "s*b":"Blue supergiant star",
  "Gr?":"Possible Group of Galaxies",
  "gB":"gamma-ray Burst",
  "AM*":"CV of AM Her type (polar)",
  "DNe":"Dark Cloud (nebula)",
  "HzG":"Galaxy with high redshift",
  "RG*":"Red Giant Branch star",
  "LI?":"Possible gravitationally lensed image",
  "Sy?":"Symbiotic Star Candidate",
  "bub":"Bubble",
  "PaG":"Pair of Galaxies",
  "cir":"CircumStellar matter",
  "HII":"HII (ionized) region",
  "LS?":"Possible gravitational lens System",
  "Cl*":"Cluster of Stars",
  "EP*":"Star showing eclipses by its planet",
  "GrG":"Group of Galaxies",
  "Sy*":"Symbiotic Star",
  "Y*O":"Young Stellar Object",
  "Fl*":"Flare Star",
  "El*":"Ellipsoidal variable Star",
  "X":"X-ray source",
  "Al*":"Eclipsing binary of Algol type (detached)",
  "Y*?":"Young Stellar Object Candidate",
  "LP*":"Long-period variable star",
  "ERO":"Extremely Red Object"
}